### ISSUE TITLE
[월간회고] 2024.01

### ISSUE THREAD

**Issue by Sleepingoff** [code-record/retrospect001#2]
안녕하세요! 회고 스터디가 유예되면서 설 기간이 애매하게 껴버렸어요~ 
그래서 이번에는 월간 회고로 진행하고 설이 지난 이후에 주간 회고를 계획하고 있습니다!

## 월간 회고 진행
일정: 1월 27일 토요일 오후 8시
장소: 디스코드 음성채널 회고방

과제: 각자의 회고 방식으로 블로그 글 써오기
블로그 링크는 아래 댓글로 달아주세요!

**Comment by LogInDev** [comment]
https://leaf-manatee-f83.notion.site/24-01-2cd7466cf0b2488fbd3f8f9350ce8bca?pvs=4

**Comment by Sleepingoff** [comment]
https://egg-developer.tistory.com/32
